#spring:
#  application:name=login

spring:
  application:
    name: login

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: { datasource-pw }
    url: { datasource-url }

  mail:
    host: smtp.gmail.com
    port: 587
    username: { smtp-username }
    password: { smtp-pw }
    properties:
      mail:
        smtp:
          auth: true #SMTP 서버에 인증이 필요한 경우 true로 지정(Gmail은 요구됨)
          starttls:
            enable: true #SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정
            required: true
          connection-timeout: 5000
          # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          timeout: 5000 #클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간
          write-timeout: 5000 #클라이언트가 작업을 완료하는 데 대기해야 하는 시간
        mime:
          charset: UTF-8
    auth-code-expiration-millis: 300000 #1000*60*5 = 5분 (이메일 인증코드의 만료 시간)

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: { client-id }
            client-secret: { client-secret }
            redirect-uri: { redirect-uri }
          kakao:
            client-id: { client-id }
            client-secret: { client-secret }
            redirect-uri: { redirect-uri }
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret: { jwt-secret }
