#spring:
#  application:name=login

spring:
  application:
    name: login

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1151
    url: jdbc:mysql://localhost:3306/login?useSSL=false&allowPublicKeyRetrieval=true

  mail:
    host: smtp.gmail.com
    port: 587
    username: {gmail username}
    password: {smtp 용 비밀번호}
    properties:
      mail:
        smtp:
          auth: true #SMTP 서버에 인증이 필요한 경우 true로 지정(Gmail은 요구됨)
          starttls:
            enable: true #SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정
            required: true
          connection-timeout: 5000
          # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          timeout: 5000 #클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간
          write-timeout: 5000 #클라이언트가 작업을 완료하는 데 대기해야 하는 시간
    auth-code-expiration-millis: 300000 #1000*60*5 = 5분 (이메일 인증코드의 만료 시간)

  data:
    redis:
      host: localhost
      port: 6379
      password: {redis 비밀번호}

jwt:
  secret: {jwt.secret 키}

# mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=testnz2412@gmail.com
##(??? ???? ????)
#spring.mail.password=x r i s u q j n l o s b u u i i
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
